# ────────────────────────────
# 🌐 Site & Theme
# ────────────────────────────
theme: jekyll-theme-chirpy
lang: en
timezone: America/Bogota   # ← antes vacío
google_analytics:
  id: G-86F3LY0CXK

# ────────────────────────────
# 🔎 SEO / Branding
# ────────────────────────────
title: "☁️Archives of a Space Dust"
tagline: "Posts on Azure, development, and GenAI"
description: >-
  This repository contains a collection of blog posts covering topics related
  to Azure cloud services, software development, and OpenAI services. Explore
  articles on building applications on Azure, leveraging developer tools and
  frameworks, and harnessing the power of OpenAI technologies. Stay updated
  with the latest trends, tips, and tutorials in these domains and unlock the
  potential of cloud computing, cutting-edge development techniques, and
  AI-driven solutions.

url: "https://spacedustlab.github.io"
baseurl: ""          # (sin dominio personalizado)

# ────────────────────────────
# 👤 Social profiles
# ────────────────────────────
github:
  username: spacedustlab
twitter:
  username: 

social:
  name: space dust
  email: 
  links:
    - https://github.com/spacedustlab
    # - https://www.linkedin.com/in/haejung-koh
# ────────────────────────────
# 📈 Analytics
# ────────────────────────────
analytics:
  google:
    id: G-86F3LY0CXK
  goatcounter:
    id: warnov.goatcounter.com
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider: goatcounter   # ← antes vacío

# ────────────────────────────
# 💬 Comments
# ────────────────────────────
comments:
  provider: disqus
  disqus:
    shortname: devcloudfusion
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# ────────────────────────────
# 🖼  Media / Assets
# ────────────────────────────
avatar: "/assets/img/avatar.png"
social_preview_image: "/assets/img/avatar.png"

assets:
  self_host:
    enabled: true          # ← heredado
    env:                   # (vacío → aplica a ambos entornos)

# ────────────────────────────
# 📐 Layout & Features
# ────────────────────────────
toc: true
theme_mode:               # (sigue sistema)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

# ────────────────────────────
# ⚙️  Defaults / Collections (sin cambios)
# ────────────────────────────
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# ────────────────────────────
# 📂 Exclude (fusión de ambas listas)
# ────────────────────────────
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# ────────────────────────────
# 🏷 Archives
# ────────────────────────────
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
